{
 "title": "Kyverno Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Violation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kyverno_total_count_of_violations"
    }
   ]
  },
  {
   "title": "Total Violation on Audit Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kyverno_no_violation_on_audit_mode"
    }
   ]
  },
  {
   "title": "Total Violation on Enforce Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kyverno_no_violation_on_audit_mode"
    }
   ]
  },
  {
   "title": "Total Audit Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kyverno_number_of_audit_policies"
    }
   ]
  },
  {
   "title": "Total Successful Policy Application",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kyverno_tc_successful_policy_application"
    }
   ]
  }
 ]
}