---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kv-sa
  namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kv-cluster-role
  namespace: kyverno
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kv-cluster-role-binding
  namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kv-cluster-role
subjects:
  - kind: ServiceAccount
    name: kv-sa
    namespace: kyverno
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kv-exporter
  name: kv-exporter
  namespace: kyverno
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kv-exporter
  template:
    metadata:
      labels:
        app: kv-exporter
    spec:
      serviceAccountName: kv-sa
      containers:
        - image: imrajdas/kv-exporter:ci
          imagePullPolicy: Always
          name: kv-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kv-exporter
  name: kv-exporter
  namespace: kyverno
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kv-exporter
  type: NodePort
---
# Prometheus tunables
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-tunables
  namespace: kyverno
data:
  storage-retention: 24h
---
# Define the openebs prometheus jobs
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kyverno
apiVersion: v1
data:
  prometheus.yml: |-
    global:
      external_labels:
        app: kv-exporter
      scrape_interval: 10s
      evaluation_interval: 10s
    rule_files:
      - "/etc/prometheus-rules/*.rules"
    scrape_configs:
    - job_name: 'kv-exporter'
      static_configs:
        - targets: ['kv-exporter.kyverno.svc.cluster.local:8080']
---
# prometheus-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kyverno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.11.0
          args:
            - "--config.file=/etc/prometheus/conf/prometheus.yml"
            # Metrics are stored in an emptyDir volume which
            # exists as long as the Pod is running on that Node.
            # The data in an emptyDir volume is safe across container crashes.
            - "--storage.tsdb.path=/prometheus"
            # How long to retain samples in the local storage.
            - "--storage.tsdb.retention=$(STORAGE_RETENTION)"
          ports:
            - containerPort: 9090
          env:
            # environment vars are stored in prometheus-env configmap.
            - name: STORAGE_RETENTION
              valueFrom:
                configMapKeyRef:
                  name: prometheus-tunables
                  key: storage-retention
          volumeMounts:
            # prometheus config file stored in the given mountpath
            - name: prometheus-server-volume
              mountPath: /etc/prometheus/conf
            # metrics collected by prometheus will be stored at the given mountpath.
            - name: prometheus-storage-volume
              mountPath: /prometheus
      volumes:
        # Prometheus Config file will be stored in this volume
        - name: prometheus-server-volume
          configMap:
            name: prometheus-config
        # All the time series stored in this volume in form of .db file.
        - name: prometheus-storage-volume
          # containers in the Pod can all read and write the same files here.
          emptyDir: {}
---
# prometheus-service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: kyverno
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - port: 80 # this Service's port (cluster-internal IP clusterIP)
      targetPort: 9090 # pods expose this port
      # Note that this Service will be visible as both NodeIP:nodePort and clusterIp:Port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kyverno
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "kyverno-metrics",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.kyverno.svc.cluster.local:80",
                "version": 1
            }
        ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kyverno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources
              name: grafana-datasources
              readOnly: false
            - mountPath: /var/lib/grafana
              name: grafana-storage
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kyverno
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000